# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

pod 'Firebase/Core'
pod 'Firebase/Database'
pod 'react-native-sqlite-storage', :path => '../node_modules/react-native-sqlite-storage'

target 'BattleBuddy' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for BattleBuddy

  target 'BattleBuddy-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'BattleBuddyTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
